# This workflow will install Python dependencies, build the module, run tests and style checks
# for several python versions on the latest ubuntu-release.

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup virtual environment and install dependencies
      run: |
        ./install_setup.sh

    - name: Build module
      run: |
        . env/bin/activate; make build

    - name: Run PEP8 style check
      run: |
        . env/bin/activate; make check-pep8

    - name: Run clang-format style check
      run: |
        . env/bin/activate; make check-clang-format

    - name: Run clang-tidy modernization checks
      run: |
        . env/bin/activate; make check-clang-tidy

    - name: Run tests
      run: |
        . env/bin/activate; make test
